#! /bin/sh
### BEGIN INIT INFO
# Provides:          tomcat
# Required-Start:    $time
# Required-Stop:
# Should-Start:      glibc
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6
# Short-Description: Manage Tomcat
# Description:       Start Stop and Restart Tomcat.
### END INIT INFO
# Tomcat Startup Script

HOME=/opt/sdc-client/server
JRE_HOME=/usr/lib/jvm/java-6-sun-1.6.0.26; export JRE_HOME

start() {
        echo -n "Starting Tomcat:  "
	  cd $HOME/bin
	  ./catalina.sh run
}
stop() {
        echo -n "Stopping Tomcat: "
	  cd $HOME/bin
	  ./shutdown.sh
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo $"Usage: tomcat {start|stop|restart}"
        exit
esac
